Hello,<br><br>My question concerns the display of error message generated by a throw std::runtime_error(&quot;Explicit error message&quot;).<br>I am launching on a terminal an openMPI program on several machines using:<br>
mpirun -v -machinefile MyMachineFile.txt MyProgram.<br>I am wondering why I cannot see an error message displayed on the terminal when one of my distant node (meaning not the node where the terminal is used) is crashing. I was expecting that following try catch could also generates a display in the terminal:<br>
try {...My code where a crash happens... } <br>{<br>  throw std::runtime_error( &quot;Explicit error message&quot; );<br>}<br><br>Generally, my problem is that one of the node crashes and the global application waits forever data from this node. On the terminal, nothing is displayed indicating that the node has crashed and generated a useful information of the crash nature.<br>
<br>( I don&#39;t think these information are relevant here, but just in case: I am using openMPI 1.4.2, on a Mandriva 2008 system )<br><br>Thanks in advance for any help/info/advice.<br><br>Olivier<br>

