<html><head><meta http-equiv="Content-Type" content="text/html charset=us-ascii"></head><body style="word-wrap: break-word; -webkit-nbsp-mode: space; -webkit-line-break: after-white-space;">Hmmm....I would guess you should talk to the Hadoop folks as the problem seems to be a conflict between valgrind and HDFS. Does valgrind even support Java programs? I honestly have never tried to do that before.<div><br></div><div><br><div><div>On Oct 2, 2014, at 4:40 AM, XingFENG &lt;<a href="mailto:xingfeng@cse.unsw.edu.au">xingfeng@cse.unsw.edu.au</a>&gt; wrote:</div><br class="Apple-interchange-newline"><blockquote type="cite"><div dir="ltr">Hi there,<br><br>I am using valgrind to help analyse my MPI program.<br><br>I used hdfs file system to read/write data. And if I run the code without valgrind, it works correctly. However, if I run with valgrind, for example, <br clear="all"><div><br><i>mpirun -np 3 /usr/bin/valgrind --tool=callgrind&nbsp; ./myprogram /input_file /output_file</i><br><br></div><div>it returns with following information<br><br>=========================================================<br><i>Exception in thread "main" java.lang.InternalError: processing event: 535548453<br>&nbsp;&nbsp;&nbsp; at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:506)<br>&nbsp;&nbsp;&nbsp; at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)<br>&nbsp;&nbsp;&nbsp; at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)<br>&nbsp;&nbsp;&nbsp; at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)<br>&nbsp;&nbsp;&nbsp; at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)<br>&nbsp;&nbsp;&nbsp; at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)<br>&nbsp;&nbsp;&nbsp; at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:177)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:1156)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:1107)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:1053)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.conf.Configuration.get(Configuration.java:397)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.conf.Configuration.getBoolean(Configuration.java:594)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.security.SecurityUtil.&lt;clinit&gt;(SecurityUtil.java:67)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.net.NetUtils.makeSocketAddr(NetUtils.java:188)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.net.NetUtils.createSocketAddr(NetUtils.java:168)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.hdfs.server.namenode.NameNode.getAddress(NameNode.java:212)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:99)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1446)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:67)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1464)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:263)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.fs.FileSystem$1.run(FileSystem.java:118)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.fs.FileSystem$1.run(FileSystem.java:116)<br>&nbsp;&nbsp;&nbsp; at java.security.AccessController.doPrivileged(Native Method)<br>&nbsp;&nbsp;&nbsp; at javax.security.auth.Subject.doAs(Subject.java:415)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)<br>&nbsp;&nbsp;&nbsp; at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:116)<br>Call to org.apache.hadoop.fs.Filesystem::get(URI, Configuration) failed!<br></i><br><br>=========================================================<br></div><div><br></div>By debugging, I found that the exception happens in hdfsConnect(). But I don't how to fix it. Could anyone give me some advice, please?<br><div><br>-- <br><div dir="ltr">Best Regards.<br>---<br>Xing FENG<div>PhD Candidate<br>Database Research Group<br><br></div><div>School of Computer Science and Engineering<div>University of New South Wales<br></div>NSW 2052, Sydney<br></div><div><br></div><div>Phone: (+61) 413 857 288</div></div>
</div></div>
_______________________________________________<br>users mailing list<br><a href="mailto:users@open-mpi.org">users@open-mpi.org</a><br>Subscription: http://www.open-mpi.org/mailman/listinfo.cgi/users<br>Link to this post: http://www.open-mpi.org/community/lists/users/2014/10/25425.php</blockquote></div><br></div></body></html>
