<div dir="ltr">Hi Siegmar,<div><br></div><div>Sorry for the delay, I seem to have missed this one.</div><div><br></div><div>It looks like there&#39;s an error in the way the native methods are processing</div><div>java exceptions.  The code correctly builds up an exception message for</div><div>cases where MPI &#39;c&#39; returns non-success but, not if the problem occured</div><div>in one of the JNI utilities.  </div><div><br></div><div>Issue filed:</div><div><a href="https://github.com/open-mpi/ompi/issues/1698">https://github.com/open-mpi/ompi/issues/1698</a><br></div><div><br></div><div><br></div><div>Thanks for reporting this.</div><div><br></div><div><br></div><div>Howard</div><div><br></div></div><div class="gmail_extra"><br><div class="gmail_quote">2016-05-20 9:25 GMT-06:00 Siegmar Gross <span dir="ltr">&lt;<a href="mailto:siegmar.gross@informatik.hs-fulda.de" target="_blank">siegmar.gross@informatik.hs-fulda.de</a>&gt;</span>:<br><blockquote class="gmail_quote" style="margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-left:1ex">Hi,<br>
<br>
I tried MPI.ERRORS_RETURN in a small Java program with Open MPI<br>
1.10.2 and master. I get the expected behaviour, if I use a<br>
wrong value for the root process in &quot;bcast&quot;. Unfortunately I<br>
get an MPI or Java error message if I try to broadcast more data<br>
than available. Is this intended or is it a problem in the Java<br>
interface of Open MPI? I would be grateful if somebody can answer<br>
my question.<br>
<br>
loki java 194 mpijavac Exception_1_Main.java<br>
loki java 195 mpijavac Exception_2_Main.java<br>
<br>
loki java 196 mpiexec -np 1 java Exception_1_Main<br>
Set error handler for MPI.COMM_WORLD to MPI.ERRORS_RETURN.<br>
Call &quot;bcast&quot; with wrong &quot;root&quot; process.<br>
Caught an exception.<br>
MPI_ERR_ROOT: invalid root<br>
<br>
<br>
loki java 197 mpiexec -np 1 java Exception_2_Main<br>
Set error handler for MPI.COMM_WORLD to MPI.ERRORS_RETURN.<br>
Call &quot;bcast&quot; with index out-of bounds.<br>
Exception in thread &quot;main&quot; java.lang.ArrayIndexOutOfBoundsException<br>
        at mpi.Comm.bcast(Native Method)<br>
        at mpi.Comm.bcast(Comm.java:1231)<br>
        at Exception_2_Main.main(Exception_2_Main.java:44)<br>
-------------------------------------------------------<br>
Primary job  terminated normally, but 1 process returned<br>
a non-zero exit code.. Per user-direction, the job has been aborted.<br>
-------------------------------------------------------<br>
--------------------------------------------------------------------------<br>
mpiexec detected that one or more processes exited with non-zero status, thus causing<br>
the job to be terminated. The first process to do so was:<br>
<br>
  Process name: [[38300,1],0]<br>
  Exit code:    1<br>
--------------------------------------------------------------------------<br>
loki java 198<br>
<br>
<br>
Kind regards and thank you very much for any help in advance<span class="HOEnZb"><font color="#888888"><br>
<br>
Siegmar<br>
</font></span><br>_______________________________________________<br>
users mailing list<br>
<a href="mailto:users@open-mpi.org">users@open-mpi.org</a><br>
Subscription: <a href="https://www.open-mpi.org/mailman/listinfo.cgi/users" rel="noreferrer" target="_blank">https://www.open-mpi.org/mailman/listinfo.cgi/users</a><br>
Link to this post: <a href="http://www.open-mpi.org/community/lists/users/2016/05/29256.php" rel="noreferrer" target="_blank">http://www.open-mpi.org/community/lists/users/2016/05/29256.php</a><br></blockquote></div><br></div>

